sources:
  - name: AssetsService
    handler:
      openapi:
        endpoint: http://localhost:3002/
        source: ../assets-service/openapi3-definition.json
  - name: PublishersService
    handler:
      openapi:
        endpoint: http://localhost:3003/
        source: ../publishers-service/openapi3-definition.json
  - name: UsersService
    handler:
      openapi:
        endpoint: http://localhost:3004/
        source: ../users-service/openapi3-definition.json
  - name: Stores
    handler:
      graphql:
        endpoint: http://0.0.0.0:3005/graphql
transforms:
  - filterSchema:
      filters:
        - Asset.!categoryId
        - Asset.!publisherId
        - User.!entitlementsIds
        - Sells.!assetId
plugins:
  - deduplicateRequest: {}
  - maskedErrors:
      errorMessage: 'Something went wrong.'
#  - httpDetailsExtensions: {}
additionalTypeDefs: |
  extend type Asset {
    publisher: Publisher
    category: Category
  }
  extend type User {
    entitlements: [Asset]
  }
  extend type Sells {
    asset: Asset
  }
additionalResolvers:
  - targetTypeName: Asset
    targetFieldName: category
    sourceName: AssetsService # Which source does the target field belong to?
    sourceTypeName: Query # Which root type does the target field belong to?
    sourceFieldName: category # What is the source field name?
    requiredSelectionSet:
      |
      {
        categoryId
      }
    sourceArgs: # What args does this need to take?
      id: "{root.categoryId}"
  - targetTypeName: Asset
    targetFieldName: publisher
    sourceName: PublishersService # Which source does the target field belong to?
    sourceTypeName: Query # Which root type does the target field belong to?
    sourceFieldName: publisher # What is the source field name?
    requiredSelectionSet:
      |
      {
        publisherId
      }
    sourceArgs: # What args does this need to take?
      id: "{root.publisherId}"
  - targetTypeName: Sells
    targetFieldName: asset
    sourceName: AssetsService # Which source does the target field belong to?
    sourceTypeName: Query # Which root type does the target field belong to?
    sourceFieldName: asset # What is the source field name?
    requiredSelectionSet:
      |
      {
        assetId
      }
    sourceArgs: # What args does this need to take?
      id: "{root.assetId}"
  - "./user-entitlements-resolver"